version: "3.9"

services:
  # responsible for reading data
  sol-static-query:
    build: ./sol-static-server/nginx
    restart: unless-stopped
    ports:
    - "6000:80"
    volumes:
      - ./sol-static-files:/var/static-files


  # responsible for data modifications 
  # sol-static-command:
  # sol-general-api:
  #   build: .
  #   restart: unless-stopped
  #   command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
  #   ports:
  #     - "8080:8080"
  #   environment: &backend_environment_variables
  #     - DJANGO_ENV=production
  #     - DJANGO_DATABASE_HOST=sol-general-postgres
  #     - DJANGO_DATABASE_PORT=5432
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - DOMAIN_NAME=${DOMAIN_NAME}
  #     - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
  # reverse proxy for sol-general-api
  # sol-general-nginx-proxy:
  #   build: .sol-general-api/nginx
  #   restart: unless-stopped
  #   ports:
  #     - target: 80
  #       published: 80
  #       mode: host
  #     - target: 443
  #       published: 443
  #       mode: host
  #   volumes:
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  # database 
  sol-general-postgres:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  pgdata:
