/*
 * ITPM admin panel API
 *
 * Admin panel for Telegram chat bot, which will help to improve user interactions with the chats.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Enemy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnemyTests
    {
        // TODO uncomment below to declare an instance variable for Enemy
        //private Enemy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Enemy
            //instance = new Enemy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Enemy
        /// </summary>
        [Test]
        public void EnemyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Enemy
            //Assert.IsInstanceOf(typeof(Enemy), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Question'
        /// </summary>
        [Test]
        public void QuestionTest()
        {
            // TODO unit test for the property 'Question'
        }
        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Test]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }
        /// <summary>
        /// Test the property 'EnemyType'
        /// </summary>
        [Test]
        public void EnemyTypeTest()
        {
            // TODO unit test for the property 'EnemyType'
        }

    }

}
