openapi: 3.0.3
info:
  title: ITPM admin panel API
  version: 1.0.0
  description: Admin panel for Telegram chat bot, which will help to improve user
    interactions with the chats.
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/worlds/:
    get:
      operationId: worlds_list
      description: Worlds viewset.
      tags:
      - worlds
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/World'
          description: ''
  /api/worlds/{uuid}/:
    get:
      operationId: worlds_retrieve
      description: Worlds viewset.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this world.
        required: true
      tags:
      - worlds
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/World'
          description: ''
components:
  schemas:
    Enemy:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        question_group:
          $ref: '#/components/schemas/QuestionGroup'
        enemy_type:
          $ref: '#/components/schemas/EnemyTypeEnum'
        user:
          type: integer
      required:
      - enemy_type
      - question_group
      - user
      - uuid
    EnemyTypeEnum:
      enum:
      - CIRCLE
      type: string
      description: '* `CIRCLE` - Circle'
    Level:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        waves:
          type: array
          items:
            $ref: '#/components/schemas/Wave'
        title:
          type: string
          maxLength: 255
        description:
          type: string
        wave_order_ids:
          type: array
          items:
            type: string
            format: uuid
        world:
          type: string
          format: uuid
      required:
      - description
      - title
      - uuid
      - wave_order_ids
      - waves
      - world
    QuestionGroup:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        question:
          type: string
        answer:
          type: string
        user:
          type: integer
      required:
      - answer
      - question
      - user
      - uuid
    Wave:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        enemies:
          type: array
          items:
            $ref: '#/components/schemas/Enemy'
        delay_time:
          type: integer
          maximum: 86400000
          minimum: 1000
        enemy_order_ids:
          type: array
          items:
            type: string
            format: uuid
        level:
          type: string
          format: uuid
      required:
      - delay_time
      - enemies
      - enemy_order_ids
      - level
      - uuid
    World:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        levels:
          type: array
          items:
            $ref: '#/components/schemas/Level'
        name:
          type: string
          maxLength: 255
        description:
          type: string
        level_order_ids:
          type: array
          items:
            type: string
            format: uuid
        user:
          type: integer
      required:
      - description
      - level_order_ids
      - levels
      - name
      - user
      - uuid
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
