version: "3.9"

services:
  # sol-general-api:
  #   build: .
  #   restart: unless-stopped
  #   container_name: sol-general-api
  #   command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
  #   ports:
  #     - "8080:8080"
  #   environment: &backend_environment_variables
  #     - DJANGO_ENV=production
  #     - DJANGO_DATABASE_HOST=sol-general-postgres
  #     - DJANGO_DATABASE_PORT=5432
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - DOMAIN_NAME=${DOMAIN_NAME}
  #     - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
  # sol-general-nginx:
  #   build: ./nginx
  #   restart: unless-stopped
  #   container_name: sol-general-nginx
  #   ports:
  #     - target: 80
  #       published: 80
  #       mode: host
  #     - target: 443
  #       published: 443
  #       mode: host
  #   volumes:
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  sol-general-postgres:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  pgdata:
