/*
 * ITPM admin panel API
 *
 * Admin panel for Telegram chat bot, which will help to improve user interactions with the chats.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Enemy
    /// </summary>
    [DataContract]
    public partial class Enemy :  IEquatable<Enemy>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets EnemyType
        /// </summary>
        [DataMember(Name="enemy_type", EmitDefaultValue=true)]
        public EnemyTypeEnum EnemyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Enemy" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Enemy() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Enemy" /> class.
        /// </summary>
        /// <param name="question">question (required).</param>
        /// <param name="answer">answer (required).</param>
        /// <param name="enemyType">enemyType (required).</param>
        public Enemy(string question = default(string), string answer = default(string), EnemyTypeEnum enemyType = default(EnemyTypeEnum))
        {
            // to ensure "question" is required (not null)
            if (question == null)
            {
                throw new InvalidDataException("question is a required property for Enemy and cannot be null");
            }
            else
            {
                this.Question = question;
            }

            // to ensure "answer" is required (not null)
            if (answer == null)
            {
                throw new InvalidDataException("answer is a required property for Enemy and cannot be null");
            }
            else
            {
                this.Answer = answer;
            }

            // to ensure "enemyType" is required (not null)
            if (enemyType == null)
            {
                throw new InvalidDataException("enemyType is a required property for Enemy and cannot be null");
            }
            else
            {
                this.EnemyType = enemyType;
            }

        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public int Id { get; private set; }

        /// <summary>
        /// Gets or Sets Question
        /// </summary>
        [DataMember(Name="question", EmitDefaultValue=true)]
        public string Question { get; set; }

        /// <summary>
        /// Gets or Sets Answer
        /// </summary>
        [DataMember(Name="answer", EmitDefaultValue=true)]
        public string Answer { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Enemy {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Question: ").Append(Question).Append("\n");
            sb.Append("  Answer: ").Append(Answer).Append("\n");
            sb.Append("  EnemyType: ").Append(EnemyType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Enemy);
        }

        /// <summary>
        /// Returns true if Enemy instances are equal
        /// </summary>
        /// <param name="input">Instance of Enemy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Enemy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Question == input.Question ||
                    (this.Question != null &&
                    this.Question.Equals(input.Question))
                ) && 
                (
                    this.Answer == input.Answer ||
                    (this.Answer != null &&
                    this.Answer.Equals(input.Answer))
                ) && 
                (
                    this.EnemyType == input.EnemyType ||
                    (this.EnemyType != null &&
                    this.EnemyType.Equals(input.EnemyType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Question != null)
                    hashCode = hashCode * 59 + this.Question.GetHashCode();
                if (this.Answer != null)
                    hashCode = hashCode * 59 + this.Answer.GetHashCode();
                if (this.EnemyType != null)
                    hashCode = hashCode * 59 + this.EnemyType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
