/*
 * ITPM admin panel API
 *
 * Admin panel for Telegram chat bot, which will help to improve user interactions with the chats.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// * &#x60;CIRCLE&#x60; - Circle
    /// </summary>
    /// <value>* &#x60;CIRCLE&#x60; - Circle</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EnemyTypeEnum
    {
        /// <summary>
        /// Enum CIRCLE for value: CIRCLE
        /// </summary>
        [EnumMember(Value = "CIRCLE")]
        CIRCLE = 1

    }

}
